#!/bin/bash
######################################
##
## Script to start several VMs at once
##
######################################


# Define colors for output messages
ERROR="$(tput setaf 1)[-]$(tput sgr0)";
GOOD="$(tput setaf 2)[+]$(tput sgr0)";
WARN="$(tput setaf 3)[*]$(tput sgr0)";


# Checking privileges
if [ $UID != 0 ]; then
	sudo $0 $@;
	exit 0;
fi

# If no arguments just list
if [ $# == 0 ]; then
	virsh list --all;
	exit 0
fi

# If there's arguments
start_vms="";
ACTION="virsh start";
output="";

if [ $1 == "--all" ] || [ $1 == "-a" ]; then
	cmd=`virsh list --name --all`;
	for vm in $cmd; do
		start_vms=$start_vms" "$vm;
	done
else
	start_vms=$@;
fi

for vm in $start_vms; do
	output=$($ACTION $vm 2>&1);
	if [[ "$output" == "error"* ]]; then
		if [[ "$output" == *"already active"* ]]; then
			printf "$WARN $vm alredy active\n";
		elif [[ "$output" == *"failed to get domain"* ]]; then
			printf "$ERROR $vm not found\n";
		else
			printf "$ERROR $vm had an unexpected error: $output\n";
		fi
	else
		printf "$GOOD $vm started\n";
	fi
done

exit 0;
